# 1. PUNTO DI PARTENZA: Immagine ufficiale di pgvector per la major version di Postgres 17
# Questo tag è più generico e viene aggiornato più di frequente.
FROM postgres:16

# Imposta bash come shell di default per root
SHELL ["/bin/bash", "-c"]

USER root

WORKDIR /tmp

RUN apt-get update && \ 
    apt-get install -y curl bash wget  postgresql-server-dev-16 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/pgsty/pig/releases/download/v0.5.0/pig-v0.5.0.linux-amd64.tar.gz && \
    tar -xzf pig-v0.5.0.linux-amd64.tar.gz && \
    cd pig-v0.5.0.linux-amd64 && \
    ls -l && \
    chmod +x pig && \
    mv pig /usr/local/bin/ && \
    chmod +x /usr/local/bin/pig


RUN pig repo add pigsty pgdg -u
RUN pig update
RUN pig ext install pgvector
RUN pig ext install duckdb_fdw
RUN pig ext install pg_cron
RUN pig ext install pgml